Homework
andrew-nvkv/hh-school-2021-java-collections-stream pull request #1
Opened 2021-12-20 08:21 UTC by andrew-nvkv

Замечания по заданиям:

1:
Написал преобразование в Map через стрим, так как не нашел более тривиального способа, как в случае с преобразованием списка в множество.
Ассимптотика: создание вспомогательной хеш-карты за O(n), формирование итогового множества тоже O(n).

2:
Был вариант использовать Stream.of(persons1, persons2). В теме на stackoverflow видел оба варианта, не уверен какой лучше.

8:
Все замечания в комментариях в коде.

2021-12-22 15:51 UTC, genroelgvozo requested changes

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task1.java
> +    // если нужно обрабатывать неуникальные id, в итоге нельзя будет использовать хеш-карту
кажется что вообще ничего не изменится, кроме третьего параметра. При не уникальных айди ты как бы и не знаешь какую выбрать. А сервис вполне может выдать дубликаты их можно отсеять

Но в итоге код сам ок

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task2.java
> +            .collect(Collectors.toList());
ок, конкат норм

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task3.java
> +            .collect(Collectors.toList());
ок

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task4.java
> +            .collect(Collectors.toList());
ок, но скобочка что-то съехала)

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task5.java
> +            .collect(Collectors.toList());
ок

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task6.java
> +            .collect(Collectors.toSet());
все ок

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task7.java
> +            .collect(Collectors.toSet());
все ок

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task8.java
> +            .collect(Collectors.toList());
ок, кроме дешевле список еще может быть неизменяемый (да и вообще трогать чужие списки не красиво)

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return new HashSet<String>(getNames(persons));
String не нужен тоже)

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    // переписано в функциональном стиле
ага, со стек оверфлоу то взял "функиональный стиль", только зачем список плодить саплаеров (еще и память ест), если можно Stream.of(getSecondName...).filter() и как ты написал?
хотя бы тогда не лямбду юзал, а ссылку на геттер, и такое выносят в статик финал поле (чтобы не создавать каждый раз). Но на прямую стрим оф читабельнее

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task8.java
> +            );
ок

2021-12-22 15:51 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    // тут стримы не нужны, просто использование стандартных методов интерфейса Collection
можно и так, а можно
.stream().anyMatch() просто короче
или Collections.disjoint()

2021-12-23 10:41 UTC, andrew-nvkv commented on src/tasks/Task8.java
> +    // тут стримы не нужны, просто использование стандартных методов интерфейса Collection
`Collections.disjoint()` видел в доках, но он анализирует списки на _отсутствие_ пересечений, то есть там не будет раннего возврата.
C `anyMatch` получится такой вариант (подсмотрел на SO преобразование во множество для оптимизации):
```
return persons2.stream()
    .anyMatch(new HashSet<Person>(persons1)::contains);
```

2021-12-23 10:56 UTC, andrew-nvkv commented on src/tasks/Task8.java
> +    // переписано в функциональном стиле
Тут действительно можно было обойтись без списка трансформаторов:
```
return Stream.of(
        person.getSecondName(),
        person.getFirstName(),
        person.getMiddleName()
    )
    .filter(Objects::nonNull)   // тут тоже увидел что можно заменить ссылкой на стандартный метод
    .collect(Collectors.joining(" "));
```
Список с функциями может быть больше полезен для `Function` интерфейсов чем для `Supplier`. Например, если у нас есть список значений, и нужно их использовать как аргументы для функций из другого списка.
Еще Java не позволяет создать список с лямбда-функциями через `Stream.of()`, нужно было создавать промежуточную переменную. Можно это как-то обойти?

2021-12-25 08:44 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    // переписано в функциональном стиле
про Function ничего не понял (как может быть что-то полезно для функции, если функция должна быть полезна для тебя?)) ты кажется перепутал инструмент и цель). То что ты хотел написать делается так
```
private static final List<Function<Person, String>> FIELDS_GETTERS = List.of(
  Person::getSecondName,
  Person::getFirstName,
  Person::getMiddleName
);
...
return FIELDS_GETTERS.stream().map(getter -> getter.apply(person)).filter(..).collect(..);

```
но никак не создавать каждый раз из саплаеров (которые тут же используешь)

Про Stream.of нельзя, потому лямбда функция не имеет конкретного типа, она может притворять очень разными функциональными интерфейсами (твоими в том числе), поэтому только явный каст помог бы (но это криво). Но это все равно создание этих саплаеров на месте, даже без переменной листа, это же такие же объекты, занимают память

2021-12-25 08:44 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    // переписано в функциональном стиле
короче не надо так делать

2021-12-25 08:44 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    // переписано в функциональном стиле
через статик поле как я написал - можно. Но не в этом случае, тут слишком простой код чтобы так его усложнять. Но в целом такой подход имеет смысл, например в паттерне стратегия - мапа чего-то на функцию, которая выбирается в зависимости от поля

2021-12-25 08:45 UTC, genroelgvozo approved these changes

2022-01-22 15:12 UTC, merged